feat#22/로그인 로그아웃 로직 구현
woowa-techcamp-2024/Team2-Dari pull request #37
Opened 2024-08-13 17:37 UTC by kkyu0718

## 📄 작업 설명
- spring-session 적용하여 서블릿 컨테이너 세션이 아닌 애플리케이션 레벨에서의 세션을 사용 -> 구현체(redis, jdbc) 를 바꿀 때 용이함
- 로그인 로그아웃 로직 구현 및 테스트 코드 작성

## 🚨 관련 이슈
closes #22 

## 🌈 작업 상황
- spring-session 코드 작성 완료하였으나 논의하고 싶은 부분이 있습니다. 직접 코멘트 달도록 하겠습니다.

2024-08-14 14:54 UTC, HyeonJun0530 requested changes
리뷰 작성한 코드를 제외하고는 나머지 코드는 큰 문제 없어 보이네요 👍 
리뷰도 그렇게 한 이유가 있다면 괜찮을 거 같아요 !
천천히 보시고 답글 부탁드려요 😊

2024-08-14 14:54 UTC, HyeonJun0530 commented on src/main/java/com/wootecam/festivals/domain/auth/controller/AuthController.java
> +    public ApiResponse<Void> login(@RequestBody LoginRequest dto) {
@Valid 어노테이션이 빠져있네요 !

2024-08-14 14:54 UTC, HyeonJun0530 commented on src/main/java/com/wootecam/festivals/domain/auth/dto/LoginRequest.java
> +        String email) {
@Email 이라는 어노테이션을 사용해 Email을 Valid 하는 것이 좋아보이네요 !
혹시 Size를 사용한 다른 이유가 있으실까요?

2024-08-14 14:54 UTC, HyeonJun0530 commented on src/main/java/com/wootecam/festivals/global/auth/AuthArgumentResolver.java
> +
어노테이션 방식말고 이렇게 클래스 방식을 쓰셨는데 어떤 점 때문에 쓰신 건가요?

2024-08-14 14:54 UTC, HyeonJun0530 commented on src/main/java/com/wootecam/festivals/global/config/WebMvcConfig.java
> +    }
Interceptor를 bean으로 등록하지 않고 new 통해 생성해주는 이유가 무엇일까요?
bean으로 하면 MemberRepository도 필드로 존재하지 않아도 될텐데 특별한 이유가 있으신건가요?

pathPatterns 부분은 현재는 모든 로그인이 성공하는 상태라 나중에 바뀔 땐 이 부분도 상의해봐야겠네요 !

2024-08-14 14:54 UTC, HyeonJun0530 commented on src/test/java/com/wootecam/festivals/docs/utils/RestDocsSupport.java
> +    public MemberRepository memberRepository;
이 MockBean은 무슨 역할을 하는지 알 수 있을까요?

2024-08-14 14:54 UTC, HyeonJun0530 commented on src/test/java/com/wootecam/festivals/domain/auth/controller/AuthControllerTest.java
> +                        ),
제약 조건도 attribute나 optional 같은 걸로 명시해서 문서에 한번에 볼 수 있게끔 하면 좋겠어요 !

2024-08-14 14:54 UTC, HyeonJun0530 commented on src/test/java/com/wootecam/festivals/domain/auth/dto/LoginRequestTest.java
@ParameterizeTest를 활용하면 좋을 것 같아요 !
현종님이 작성한 Festival 테스트 쪽을 보시면 감이 잡히실꺼예요 !

2024-08-15 07:14 UTC, kkyu0718 commented on src/main/java/com/wootecam/festivals/domain/auth/dto/LoginRequest.java
> +        String email) {
email 어노테이션 추가하도록 하겠습니다! 저희가 별도의 유효성 검증 없이 (실제 이메일인지) 이메일을 받고 있어서 비정상적으로 길이가 긴 데이터에 대한 검증 정도는 필요하다고 생각했어요!

2024-08-15 08:54 UTC, kkyu0718 commented on src/main/java/com/wootecam/festivals/global/auth/AuthArgumentResolver.java
> +
말씀하신 방법이 더 좋아보여서 수정했습니다!

2024-08-15 08:55 UTC, kkyu0718 commented on src/main/java/com/wootecam/festivals/global/config/WebMvcConfig.java
> +    }
빈 등록 방식으로 변경하였습니다. 덕분에 memberRepository 관련 mock 다 뺐어요!

2024-08-15 08:56 UTC, kkyu0718 commented on src/test/java/com/wootecam/festivals/docs/utils/RestDocsSupport.java
> +    public MemberRepository memberRepository;
WebMvcTest 가 자동으로 WebMvcConfig 와 AuthInterceptor 를 자동으로 불러오는데 AuthInterceptor 가 MemberRepository 를 의존하기 때문에 모킹으로 해결했었어요! 

이번에 수정하면서 WebMvcTest 가 자동으로 WebMvcConfig 와 AuthInterceptor 를 불러오지 않도록 수정했습니다.

2024-08-15 08:57 UTC, kkyu0718 commented on src/test/java/com/wootecam/festivals/domain/auth/dto/LoginRequestTest.java
이거 반영해서 수정했습니다 감사해요~!

2024-08-15 08:59 UTC, kkyu0718 commented
WebMvcConfig 와 AuthInterceptor 테스트 환경에서는 등록되지 않도록 해뒀으니 참고해주세요~

2024-08-15 11:25 UTC, HyeonJun0530 approved these changes

2024-08-15 11:26 UTC, merged